"""공유 컨텍스트 읽기 유틸리티. Developer 노드와 Runtime Verifier 노드 모두 사용."""

import re

from harness.config import NAMESPACE, PROJECT_ROOT

_KNOWLEDGE_DIR = PROJECT_ROOT / "context" / "knowledge"


def read_knowledge(technology_name: str, dep_names: list[str] | None = None) -> list[tuple[str, str]]:
    """
    technology_name + dep_names 각각에 대해 knowledge 파일 읽기.
    반환: [(섹션제목, 내용), ...] — 파일 없으면 해당 항목 생략.
    각 이름에 대해 baseline(<name>.md)과 findings(<name>-llm-findings.md) 두 파일 조회.
    """
    results: list[tuple[str, str]] = []

    for name in [technology_name] + (dep_names or []):
        baseline = _KNOWLEDGE_DIR / f"{name}.md"
        if baseline.exists():
            content = baseline.read_text(encoding="utf-8").strip().replace("{NAMESPACE}", NAMESPACE)
            if content:
                results.append((f"## Technology Knowledge: {name}", content))

        findings = _KNOWLEDGE_DIR / f"{name}-llm-findings.md"
        if findings.exists():
            content = findings.read_text(encoding="utf-8").strip().replace("{NAMESPACE}", NAMESPACE)
            if content:
                results.append((
                    f"## Previous Diagnostic Findings (Unverified) [{name}]",
                    "> ⚠ Auto-generated by Runtime Verifier. Low confidence. Treat as hints only.\n\n"
                    + content,
                ))

    return results


def extract_dependencies(sub_goal_spec: str) -> list[str]:
    """
    sub_goal 섹션에서 dependency 서비스명 목록 추출.
    형식: - **dependency**: `emqx`, `step-ca`  또는  `없음`
    못 찾거나 없음이면 빈 리스트 반환.
    """
    m = re.search(r'\*\*dependency\*\*\s*:\s*(.+)', sub_goal_spec)
    if not m:
        return []
    value = m.group(1).strip()
    if "없음" in value:
        return []
    return re.findall(r'`([^`]+)`', value)
