url: http://kagent-tools.kagent:8084/mcp

developer_tools:
  - k8s_get_resources
  - k8s_get_resource_yaml
  - k8s_describe_resource
  - k8s_get_events
  - k8s_get_pod_logs
  - k8s_check_service_connectivity
  - k8s_get_available_api_resources
  - k8s_get_cluster_configuration
  - helm_get_release
  - helm_list_releases

runtime_verifier_tools:
  - k8s_get_resources
  - k8s_get_resource_yaml
  - k8s_describe_resource
  - k8s_get_events
  - k8s_get_pod_logs
  - k8s_check_service_connectivity
  - k8s_patch_resource
  - k8s_rollout
  - helm_get_release
  - helm_list_releases